### ISSUE TITLE
Publish as a crate

### ISSUE THREAD

**Issue by NonlinearFruit** [fdncred/nu_plugin_json_path#4]
This plugin is super helpful. Using it in a CI/CD pipeline is a little rough with the current install steps. Doing a `cargo install` with `register` would be great

**Comment by fdncred** [comment]
I have no idea how to publish crates. Never done it.

**Comment by NonlinearFruit** [comment]
Here are a couple examples:

Starship ([workflow](https://sourcegraph.com/github.com/starship/starship@5163dbad8d09ec77dedc906072b73623191c8c5d/-/blob/.github/workflows/release.yml?L286))
```
  cargo_publish:
    name: Publish Cargo Package
    runs-on: ubuntu-latest
    needs: [release_please, upload_artifacts]
    if: ${{ needs.release_please.outputs.release_created == 'true' }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build | Publish
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
```


mdBook ([workflow](https://sourcegraph.com/github.com/rust-lang/mdBook@e8b8f34f2bff38d9dabbe35b9a7abbb94a7abdc0/-/blob/.github/workflows/deploy.yml?L63))
```
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust (rustup)
        run: rustup update stable --no-self-update && rustup default stable
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --no-verify
```


And the docs for publishing to crates.io ([docs](https://doc.rust-lang.org/cargo/reference/publishing.html))
